[package]
name = "mice"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0.99"
rustc-hash = "2.1.1"
flate2 = { version = "1.0.17", features = ["zlib-rs"], default-features = false }
